// Package token implements bearer-token authentication for the NVMS daemon.
//
// Tokens are loaded from a file at startup (one token per line) and compared
// in constant time. Tokens are opaque random byte strings generated by
// `nvms token mint` and stored in machine root via secret tooling.
package token

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"strings"
)

// Errors surfaced by the token package.
var (
	ErrNoTokens      = errors.New("token: no tokens configured (file empty? set NVMS_TOKENS)")
	ErrInvalidToken  = errors.New("token: invalid bearer token")
	ErrTokenFileRead = errors.New("token: failed to read token file")
)

// Manager offers bearer-token check against the loaded set.
type Manager struct {
	tokens map[string]struct{} // hex-encoded token -> sentinel
}

// NewManager returns a Manager loaded from the given file path. Empty file
// or missing file returns ErrNoTokens.
func NewManager(path string) (*Manager, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrNoTokens
		}
		return nil, fmt.Errorf("%w: %v", ErrTokenFileRead, err)
	}
	m, err := FromString(string(data))
	if err != nil {
		return nil, err
	}
	return m, nil
}

// FromString parses a token set from a single newline-delimited string.
// Comments (#) and whitespace lines are ignored. Tokens must be hex-encoded.
func FromString(s string) (*Manager, error) {
	m := &Manager{tokens: map[string]struct{}{}}
	for _, line := range strings.Split(s, "\n") {
		token := strings.TrimSpace(line)
		if token == "" || strings.HasPrefix(token, "#") {
			continue
		}
		if _, err := hex.DecodeString(token); err != nil {
			return nil, fmt.Errorf("token: invalid hex token: %w", err)
		}
		m.tokens[token] = struct{}{}
	}
	if len(m.tokens) == 0 {
		return nil, ErrNoTokens
	}
	return m, nil
}

// NewFromHex builds a Manager from a slice of hex-encoded tokens directly.
// Useful for tests.
func NewFromHex(tokens []string) (*Manager, error) {
	m := &Manager{tokens: map[string]struct{}{}}
	for _, t := range tokens {
		if _, err := hex.DecodeString(t); err != nil {
			return nil, fmt.Errorf("token: invalid hex: %w", err)
		}
		m.tokens[t] = struct{}{}
	}
	if len(m.tokens) == 0 {
		return nil, ErrNoTokens
	}
	return m, nil
}

// MintToken generates a new random bearer token. Returns a hex-encoded
// 32-byte (256-bit) value suitable for storing in the token file.
func MintToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("token: rand.Read failed: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// Check verifies a bearer token using constant-time comparison.
// Returns ErrInvalidToken if the candidate is missing or unknown.
func (m *Manager) Check(candidate string) error {
	if candidate == "" {
		return ErrInvalidToken
	}
	for t := range m.tokens {
		// Length-equal comparison preserves the constant-time property:
		// the worst case is a full map scan, but each comparison is O(1).
		if len(candidate) == len(t) &&
			subtle.ConstantTimeCompare([]byte(candidate), []byte(t)) == 1 {
			return nil
		}
	}
	return ErrInvalidToken
}

// Len returns the number of tokens currently loaded.
func (m *Manager) Len() int { return len(m.tokens) }
