name: Security Guard
on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  trivy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Run Trivy
        uses: aquasecurity/trivy-action@c07df6fec6fa692e6fd1200d50aaa1fdd66f03c8  # was: @master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
